export const IRS_REQUEST_STATES = [
  "REQUEST_CREATED",
  "PREFLIGHT_PENDING",
  "AUTHORIZATION_SCOPE_VERIFIED",
  "POLICY_APPROVAL_PENDING",
  "APPROVED",
  "JIT_ACCESS_GRANTED",
  "QUEUED",
  "API_CREDENTIAL_CHECK",
  "API_REQUEST_SUBMITTED",
  "RESPONSE_RECEIVED",
  "RESPONSE_HASHED_AND_ENCRYPTED",
  "EVIDENCE_RECORD_CREATED",
  "PARSING_QUEUED",
  "HUMAN_REVIEW_PENDING",
  "COMPLETE"
] as const;

export const IRS_REQUEST_EXCEPTIONS = [
  "AUTHORIZATION_MISMATCH",
  "EMPLOYEE_INELIGIBLE",
  "CREDENTIAL_UNAVAILABLE",
  "UNSUPPORTED_API_PRODUCT",
  "RATE_LIMIT_BLOCKED",
  "API_REJECTED",
  "RESPONSE_VALIDATION_FAILED",
  "SECURITY_ALERT",
  "HUMAN_REVIEW_REQUIRED"
] as const;

export type IrsRequestState = typeof IRS_REQUEST_STATES[number] | typeof IRS_REQUEST_EXCEPTIONS[number];
