CREATE TABLE IF NOT EXISTS irs_live_data_requests (
  id UUID PRIMARY KEY,
  tenant_id UUID NOT NULL,
  legal_entity_id UUID NOT NULL,
  client_case_id UUID NOT NULL,
  requester_employee_id UUID NOT NULL,
  requester_persona TEXT NOT NULL,
  request_type TEXT NOT NULL CHECK (request_type IN ('TDS_TRANSCRIPT','AUTHORIZED_ACCOUNT_DATA','TIN_MATCHING','SOR_DOCUMENT')),
  taxpayer_identifier_token TEXT NOT NULL,
  requested_tax_form TEXT NOT NULL,
  requested_tax_periods JSONB NOT NULL,
  business_purpose_code TEXT NOT NULL,
  engagement_status TEXT NOT NULL,
  identity_verification_status TEXT NOT NULL,
  authorization_type TEXT NOT NULL,
  authorization_id UUID NOT NULL,
  authorization_scope_status TEXT NOT NULL,
  practitioner_eligibility_status TEXT NOT NULL,
  employee_training_status TEXT NOT NULL,
  employee_credential_status TEXT NOT NULL,
  approval_status TEXT NOT NULL DEFAULT 'PENDING',
  execution_status TEXT NOT NULL DEFAULT 'NOT_STARTED',
  audit_event_id UUID NOT NULL,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  idempotency_key TEXT NOT NULL,
  UNIQUE (tenant_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS authorized_irs_account_evidence (
  evidence_id UUID PRIMARY KEY,
  request_id UUID NOT NULL REFERENCES irs_live_data_requests(id),
  case_id UUID NOT NULL,
  tenant_id UUID NOT NULL,
  legal_entity_id UUID NOT NULL,
  source_system TEXT NOT NULL,
  product TEXT NOT NULL,
  acquisition_method TEXT NOT NULL,
  official_request_reference TEXT,
  response_received_at TIMESTAMPTZ,
  authorization_id UUID NOT NULL,
  taxpayer_form_scope JSONB NOT NULL,
  taxpayer_period_scope JSONB NOT NULL,
  authority_verified_by UUID NOT NULL,
  authority_verified_at TIMESTAMPTZ NOT NULL,
  original_payload_hash TEXT NOT NULL,
  source_verified BOOLEAN NOT NULL DEFAULT FALSE,
  immutable BOOLEAN NOT NULL DEFAULT TRUE CHECK (immutable = TRUE),
  classification TEXT NOT NULL DEFAULT 'RESTRICTED_CLIENT_TAXPAYER',
  encrypted_vault_uri TEXT NOT NULL,
  retention_policy_id TEXT NOT NULL,
  legal_hold BOOLEAN NOT NULL DEFAULT FALSE,
  parser_status TEXT NOT NULL DEFAULT 'PENDING',
  extraction_confidence NUMERIC(5,4),
  human_validation_status TEXT NOT NULL DEFAULT 'PENDING',
  parsed_transaction_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
  reconciled_status TEXT NOT NULL DEFAULT 'NOT_STARTED',
  ai_access_policy TEXT NOT NULL DEFAULT 'MINIMIZED_REDACTED_ONLY',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_irs_request_case ON irs_live_data_requests (tenant_id, client_case_id, requested_at DESC);
CREATE INDEX IF NOT EXISTS idx_irs_evidence_case ON authorized_irs_account_evidence (tenant_id, case_id, created_at DESC);
