export const refundWorkbookHeaders = {
  transmitterEfin: 'Transmitter EFIN',
  partnerProductCode: 'Partner Product Code ',
  ssbEfin: 'SSB EFIN',
  subSsbEfin: 'Sub SSB EFIN',
  sbEfin: 'SB EFIN',
  eroEfin: 'ERO EFIN',
  eroBusinessOwnerName: 'ERO Business Owner Name',
  eroBusinessName: 'ERO Business Name',
  efinOwnerName: 'EFIN Owner Name',
  officeId: 'Office ID',
  ptin: 'PTIN',
  applicationReferenceNumber: 'Application Reference Number',
  taxpayerName: 'Taxpayer Name',
  ssn: 'SSN',
  productName: 'Product Name',
  applicationCreatedDate: 'Application Created Date',
  taxYear: 'Tax Year',
  irsAckDate: 'IRS ACK Date',
  expectedAchDate: 'Expected ACH Date',
  applicationStatus: 'Application Status',
  expectedIrsRefundAmount: 'Expected IRS Refund Amount',
  actualIrsRefundAmount: 'Actual IRS Refund Amount',
  irsFundingDate: 'IRS Funding Date',
  expectedStateRefundAmount: 'Expected State Refund Amount',
  actualStateRefundAmount: 'Actual State Refund Amount',
  sitePreparationFee: 'Site Preparation Fee',
  disbursementType: 'Disbursement Type',
  danCheckNumber: 'DAN/Check Number',
  advanceApplied: 'Advance Applied',
  advanceApproved: 'Advance Approved',
  advanceLoanAmount: 'Advance Loan Amount',
  priorYearAdvanceInterest: 'PY Advance + Interest',
  priorYearMinus1AdvanceInterest: 'PY - 1 Advance + Interest',
  comments: 'Comments',
  form1040Prefix: '1040 Prefix',
} as const;

export const restrictedImportColumns = new Set([
  refundWorkbookHeaders.transmitterEfin,
  refundWorkbookHeaders.ssbEfin,
  refundWorkbookHeaders.subSsbEfin,
  refundWorkbookHeaders.sbEfin,
  refundWorkbookHeaders.eroEfin,
  refundWorkbookHeaders.ptin,
  refundWorkbookHeaders.taxpayerName,
  refundWorkbookHeaders.ssn,
  refundWorkbookHeaders.danCheckNumber,
]);

export function assertSafeRefundImportRow(row: Record<string, unknown>) {
  if (!row[refundWorkbookHeaders.ssn]) throw new Error('source_identifier_required_for_tokenization');
  return {
    taxYear: row[refundWorkbookHeaders.taxYear],
    irsAckDate: row[refundWorkbookHeaders.irsAckDate],
    expectedAchDate: row[refundWorkbookHeaders.expectedAchDate],
    applicationStatus: row[refundWorkbookHeaders.applicationStatus],
    expectedIrsRefundAmount: row[refundWorkbookHeaders.expectedIrsRefundAmount],
    actualIrsRefundAmount: row[refundWorkbookHeaders.actualIrsRefundAmount],
    irsFundingDate: row[refundWorkbookHeaders.irsFundingDate],
    expectedStateRefundAmount: row[refundWorkbookHeaders.expectedStateRefundAmount],
    actualStateRefundAmount: row[refundWorkbookHeaders.actualStateRefundAmount],
    disbursementType: row[refundWorkbookHeaders.disbursementType],
    advanceApplied: row[refundWorkbookHeaders.advanceApplied],
    advanceApproved: row[refundWorkbookHeaders.advanceApproved],
    advanceLoanAmount: row[refundWorkbookHeaders.advanceLoanAmount],
  };
}
